# my_project/experiment.yaml
EXPERIMENT:
  NAME: "Biomarker_Exps"
  MODE: "Train"
  # MODE: "Test"
  TRIAL: "Test_T1"
SYSTEM:
  # NUM_GPUS: 2
  NUM_GPUS: [1]

DATA:
  # No of clip-segments to evaluate per video
  NO_MULTI_CLIP: 4 #3
  # IMAGE_RESIZE: [416, 416]

  # #Input masks
  # NUM_MASKS: 2
  # MASK1: "subq_mask"
  # MASK2: "merlin_short_mask" #"merlin_mask"
  
VIDEO_DATA:
  CLIP_WIDTH: 15 #16
  # TEMP_SAMPLING_METHOD: "rand_temp_sampling"
  TYPE: "linear_probe_under_pleural_line" 

MODEL:
  PRETRAIN: "imagenet"
SOLVER:
  EPOCHS: 100
  # EPOCHS: 10
  # EPOCHS: 1
  INIT_LR: 0.0001 #0.001
  OPTIMIZER: adam
  # TEST_BATCH_SIZE: 64
  # TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 6 #8 - Using smaller batch size of 6 with larger input image (416x416 px)
  TRAIN_BATCH_SIZE: 4

LOGGER:
  WANDB: "online"