# my_project/experiment.yaml
EXPERIMENT:
  NAME: "Pneumothorax_Exps"
  DATASET: "DARPA-Dataset"
  MODE: "Train"
  # MODE: "Test"
  TRIAL: "img_drop_TmaxDropSavg"
SYSTEM:
  # NUM_GPUS: 2
  NUM_GPUS: [0]

DATA:
  LABEL_DICT: "darpa_labels.json"
  # No of classes
  NUM_CLASS: 2
  # Label names for reports
  LABEL_NAMES: [ 'no-sliding', 'sliding', ]
  # Label features to use
  LABEL_FEATURES: ['sliding', ]
  # No of clip-segments to evaluate per video
  NO_MULTI_CLIP: 4 #3

VIDEO_DATA:
  CLIP_WIDTH: 15 #16

MODEL:
  PRETRAIN: "imagenet"
SOLVER:
  EPOCHS: 100
  # EPOCHS: 10
  # EPOCHS: 1
  INIT_LR: 0.001
  LOSS_FUNC: cross_entropy
  OPTIMIZER: adam
  # TEST_BATCH_SIZE: 64
  # TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 8
  TRAIN_BATCH_SIZE: 4
LOGGER:
  WANDB: "online"